# Jinja2 template for SFTP Docker Compose

services:

  app:
    container_name: sftp
    image: atmoz/sftp:latest
    restart: unless-stopped

    ports:
      - "2222:22/tcp"
    volumes:
      - "/dockerdata/sftp/files:/home/files/upload"
      - "/dockerdata/sftp/ssh:/home/files/.ssh"
    networks:
      - sftp_net  

    environment:
      - TZ=America/New_York

    command: files:LetMeIn00:1000:100
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


networks:
  sftp_net:
    external: true
